name: Upload to S3

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIAUK6YLKTANNK7CJ47
          aws-secret-access-key: n0OWAvtk7+kLFafIW+dNhsqE0BMSyelsyaaiqIxv
          aws-region: us-east-1  # or your region

      - name: Upload to S3
        run: |
          aws s3 cp . s3://loggingbtk/ --recursive --exclude ".git/*"
