name: Upload to S3

on:
  push:
    branches:
      - main  # or any branch you want 

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIA6GGLGVYW3LZ7KUIY
          aws-secret-access-key: hdd0HhP57ule+z8r3B9SZmWJlLw+rYm+Cs12GYY8
          aws-region: us-east-1 # or your region

      - name: Upload to S3
        run: |
          aws s3 cp . s3://bktbktbbkt/ --recursive --exclude ".git/*"
