name: Upload zipped repo to S3 on changes

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.html'
      - '**.css'
      - '**.js'
      - '**.php'
      - '**.yml'
      - '!README.md'     # ignore if you want

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your region

      - name: Zip repo with timestamp
        run: |
          zip_name="repo-$(date +'%Y-%m-%d-%H-%M-%S').zip"
          zip -r $zip_name . -x ".git/*" ".github/*"
          echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV

      - name: Upload ZIP to S3
        run: |
          aws s3 cp $ZIP_NAME s3://bktbktbbkt/uploads/$ZIP_NAME
